x-common-variables: &common-variables
  KAFKA_BROKER: kafka:9092
  ZOOKEEPER_PORT: 2181
  KAFKA_PORT: 9092
  PRODUCER_PORT: 5000

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      <<: *common-variables

  kafka:
    image: wurstmeister/kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      <<: *common-variables
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_CREATE_TOPICS: "sensor_data:1:1"
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    ports:
      - "${PRODUCER_PORT}:${PRODUCER_PORT}"
    environment:
      <<: *common-variables
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      <<: *common-variables
    depends_on:
      - kafka