version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sensor_data:1:1"
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka